baseURL = "https://shota.coffee/"
languageCode = "ja"
title = "shotaCoffee"
publishDir = "docs"
contentDir = "post"
paginate = 3
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true

googleAnalytics = "UA-151064248-1"

[taxonomies]
tag = "tags"
