baseURL = "https://shota.coffee/"
languageCode = "js"
title = "codesign"
contentDir = "post"
hasCJKLanguage = true
summaryLength = 80

googleAnalytics = "UA-151064248-1"

[taxonomies]
tag = "tags"

[params]
favicon = "favicon.ico"