baseURL = "https://shota.coffee/"
languageCode = "ja"
title = "shotaCoffee"
theme = "harbor"
publishDir = "docs"
canonifyurls = true
paginate = 3
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

googleAnalytics = "UA-151064248-1"
# and disqus too.
# disqusShortName = "your disqusshortname"

# [params.goatcounter]
#   domain="stats.domain.com"

# [params.matomo]
#   domain="stats.domain.com"
#   id="123"

# [Author]
#   name = "Hugo Author"

# [outputs]
#   section = ["JSON", "HTML"]

# [[params.nav]]
#   identifier = "about"
#   name = "About"
#   icon = "fas fa-user fa-lg"
#   url = "/about/"
#   weight = 3

# [[params.nav]]
#   identifier = "tags"
#   name = "Tags"
#   icon = "fas fa-tag fa-lg"
#   url = "tags"
#   weight = 3

# [[params.nav]]
#   identifier = "categories"
#   name = "Category"
#   icon = "fas fa-folder-open fa-lg"
#   url = "categories"
#   weight = 3

# [[params.nav]]
#   identifier = "search"
#   name = "Search"
#   icon = "fas fa-search fa-lg"
#   url = "search"
#   weight = 3

# [[params.nav]]
#   identifier = "archives"
#   name = "Archives"
#   icon = "fas fa-archive fa-lg"
#   url = "archives"
#   weight = 3

# copy paste this block and change for each social media to add how many ever social media
# acounts/links you want
# [[params.social]]
#   name="name of social media"
#   url="link to social media"
#   icon="A icon from https://fontawesome.com/"

# [params.logo]
#   url = "icon.png" # static/images/icon.png
#   width = 50
#   height = 50
#   alt = "Logo"