baseURL = "https://shota.coffee/"
languageCode = "ja"
title = "shotaCoffee"
publishDir = "docs"
contentDir = "post"
paginate = 3
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
pygmentsCodeFences = true
pygmentsUseClasses = true
[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 2

googleAnalytics = "UA-151064248-1"

[taxonomies]
tag = "tags"
